version: '3.5'

services:
  
  api:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
        context: .
        target: development
        dockerfile: ./api/Dockerfile
    command: npm run start
    ports:
        - 8085:3000
    networks:
        - postgres
    volumes:
        - ./api/:/usr/src/app
        - /usr/src/app/node_modules
    restart: unless-stopped
  
  client:
    container_name: angular_client_dev
    image: angular_client_dev:1.0.0
    build:
        context: .
        target: development
        dockerfile: ./client/Dockerfile
    ports:
        - 8086:3000
    networks:
        - postgres
    volumes:
        - './client/:/app/client'
        - '/app/client/node_modules'
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana:7.3.6
    ports:
      - 8084:3000
    networks:
      - postgres

  postgres:
    container_name: postgres_containerbreshow
    image: postgres-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./data/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
       - ./data/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
  
  pgadmin:
    container_name: pgadmin_containerbreshow
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/root/.pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  keycloak:
    container_name: keycloak_containerbreshow
    image: jboss/keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: 5432
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      JDBC_PARAMS: "ssl=false"
      # PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - "28080:8080"
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: